defaults:
  - dataset: ???
  - model: rnndet
  - _self_

is_train: False
checkpoint: ???
use_test_set: False
reverse: False
hardware:
  num_workers:
    eval: 8
  gpus: 0 # GPU idx (multi-gpu not supported for validation)
batch_size:
  eval: 16
training:
  precision: 16
tta:
  enable: False
  hflip: True
  tflip: True
